/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const IndexLazyImport = createFileRoute('/')()
const DashboardIndexLazyImport = createFileRoute('/dashboard/')()
const SharedIdLazyImport = createFileRoute('/shared/$id')()
const DashboardNotesLazyImport = createFileRoute('/dashboard/notes')()
const DashboardNotesIdLazyImport = createFileRoute('/dashboard/notes/$id')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const DashboardLazyRoute = DashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const TestRoute = TestImport.update({
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  path: '/',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

const SharedIdLazyRoute = SharedIdLazyImport.update({
  path: '/shared/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shared/$id.lazy').then((d) => d.Route))

const DashboardNotesLazyRoute = DashboardNotesLazyImport.update({
  path: '/notes',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/notes.lazy').then((d) => d.Route),
)

const DashboardNotesIdLazyRoute = DashboardNotesIdLazyImport.update({
  path: '/$id',
  getParentRoute: () => DashboardNotesLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/notes/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/shared/$id': {
      id: '/shared/$id'
      path: '/shared/$id'
      fullPath: '/shared/$id'
      preLoaderRoute: typeof SharedIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof DashboardLazyImport
    }
    '/dashboard/notes/$id': {
      id: '/dashboard/notes/$id'
      path: '/$id'
      fullPath: '/dashboard/notes/$id'
      preLoaderRoute: typeof DashboardNotesIdLazyImport
      parentRoute: typeof DashboardNotesLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  TestRoute,
  DashboardLazyRoute: DashboardLazyRoute.addChildren({
    DashboardNotesLazyRoute: DashboardNotesLazyRoute.addChildren({
      DashboardNotesIdLazyRoute,
    }),
    DashboardIndexLazyRoute,
  }),
  LoginLazyRoute,
  SharedIdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/test",
        "/dashboard",
        "/login",
        "/shared/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.lazy.tsx",
      "children": [
        "/dashboard/notes",
        "/dashboard/"
      ]
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/dashboard/notes": {
      "filePath": "dashboard/notes.lazy.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/notes/$id"
      ]
    },
    "/shared/$id": {
      "filePath": "shared/$id.lazy.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/notes/$id": {
      "filePath": "dashboard/notes/$id.lazy.tsx",
      "parent": "/dashboard/notes"
    }
  }
}
ROUTE_MANIFEST_END */
