/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const LoginLazyRouteImport = createFileRoute('/login')()
const DashboardLazyRouteImport = createFileRoute('/dashboard')()
const IndexLazyRouteImport = createFileRoute('/')()
const DashboardIndexLazyRouteImport = createFileRoute('/dashboard/')()
const SharedIdLazyRouteImport = createFileRoute('/shared/$id')()
const DashboardSettingsLazyRouteImport = createFileRoute(
  '/dashboard/settings',
)()
const DashboardNotesLazyRouteImport = createFileRoute('/dashboard/notes')()
const DashboardNotesIdLazyRouteImport = createFileRoute(
  '/dashboard/notes/$id',
)()
const DashboardNodesChar123IdChar125LazyRouteImport = createFileRoute(
  '/dashboard/nodes/{-$id}',
)()

const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const DashboardLazyRoute = DashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const SharedIdLazyRoute = SharedIdLazyRouteImport.update({
  id: '/shared/$id',
  path: '/shared/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/shared/$id.lazy').then((d) => d.Route))
const DashboardSettingsLazyRoute = DashboardSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/settings.lazy').then((d) => d.Route),
)
const DashboardNotesLazyRoute = DashboardNotesLazyRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashboardLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/notes.lazy').then((d) => d.Route),
)
const DashboardNotesIdLazyRoute = DashboardNotesIdLazyRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardNotesLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/notes/$id.lazy').then((d) => d.Route),
)
const DashboardNodesChar123IdChar125LazyRoute =
  DashboardNodesChar123IdChar125LazyRouteImport.update({
    id: '/nodes/{-$id}',
    path: '/nodes/{-$id}',
    getParentRoute: () => DashboardLazyRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/nodes/{-$id}.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/dashboard/notes': typeof DashboardNotesLazyRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/shared/$id': typeof SharedIdLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/nodes/{-$id}': typeof DashboardNodesChar123IdChar125LazyRoute
  '/dashboard/notes/$id': typeof DashboardNotesIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/dashboard/notes': typeof DashboardNotesLazyRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/shared/$id': typeof SharedIdLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/dashboard/nodes/{-$id}': typeof DashboardNodesChar123IdChar125LazyRoute
  '/dashboard/notes/$id': typeof DashboardNotesIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/dashboard/notes': typeof DashboardNotesLazyRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsLazyRoute
  '/shared/$id': typeof SharedIdLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/nodes/{-$id}': typeof DashboardNodesChar123IdChar125LazyRoute
  '/dashboard/notes/$id': typeof DashboardNotesIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/notes'
    | '/dashboard/settings'
    | '/shared/$id'
    | '/dashboard/'
    | '/dashboard/nodes/{-$id}'
    | '/dashboard/notes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/notes'
    | '/dashboard/settings'
    | '/shared/$id'
    | '/dashboard'
    | '/dashboard/nodes/{-$id}'
    | '/dashboard/notes/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/notes'
    | '/dashboard/settings'
    | '/shared/$id'
    | '/dashboard/'
    | '/dashboard/nodes/{-$id}'
    | '/dashboard/notes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardLazyRoute: typeof DashboardLazyRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
  SharedIdLazyRoute: typeof SharedIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/shared/$id': {
      id: '/shared/$id'
      path: '/shared/$id'
      fullPath: '/shared/$id'
      preLoaderRoute: typeof SharedIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesLazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
    '/dashboard/notes/$id': {
      id: '/dashboard/notes/$id'
      path: '/$id'
      fullPath: '/dashboard/notes/$id'
      preLoaderRoute: typeof DashboardNotesIdLazyRouteImport
      parentRoute: typeof DashboardNotesLazyRoute
    }
    '/dashboard/nodes/{-$id}': {
      id: '/dashboard/nodes/{-$id}'
      path: '/nodes/{-$id}'
      fullPath: '/dashboard/nodes/{-$id}'
      preLoaderRoute: typeof DashboardNodesChar123IdChar125LazyRouteImport
      parentRoute: typeof DashboardLazyRoute
    }
  }
}

interface DashboardNotesLazyRouteChildren {
  DashboardNotesIdLazyRoute: typeof DashboardNotesIdLazyRoute
}

const DashboardNotesLazyRouteChildren: DashboardNotesLazyRouteChildren = {
  DashboardNotesIdLazyRoute: DashboardNotesIdLazyRoute,
}

const DashboardNotesLazyRouteWithChildren =
  DashboardNotesLazyRoute._addFileChildren(DashboardNotesLazyRouteChildren)

interface DashboardLazyRouteChildren {
  DashboardNotesLazyRoute: typeof DashboardNotesLazyRouteWithChildren
  DashboardSettingsLazyRoute: typeof DashboardSettingsLazyRoute
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  DashboardNodesChar123IdChar125LazyRoute: typeof DashboardNodesChar123IdChar125LazyRoute
}

const DashboardLazyRouteChildren: DashboardLazyRouteChildren = {
  DashboardNotesLazyRoute: DashboardNotesLazyRouteWithChildren,
  DashboardSettingsLazyRoute: DashboardSettingsLazyRoute,
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  DashboardNodesChar123IdChar125LazyRoute:
    DashboardNodesChar123IdChar125LazyRoute,
}

const DashboardLazyRouteWithChildren = DashboardLazyRoute._addFileChildren(
  DashboardLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardLazyRoute: DashboardLazyRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
  SharedIdLazyRoute: SharedIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
