export const TITLE_TAKEN_CODE = 1004;
export const CONNECTOR_ID_COLLISION_CODE = 1005;
export const SHARED_PASSWORD_MISSING_CODE = 1001;
export const SHARED_PASSWORD_WRONG_CODE = 1002;
export const SHARED_PRIVATE_CODE = 1003;
